package:
  name: jupconfig
  version: "0.0.3"  # Adjust the version number as needed

source:
  path: .  # Assuming the source code is in the current directory

build:
  noarch: python  # if pure Python (independent of the system architecture)

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - autologging
    - geopandas
    - json
    - pandas 
    - rioxarray
    - xarray

extra:
  channels:
    - conda-forge